"""empty message

Revision ID: 838b78bd69b3
Revises: 53c29fd98059
Create Date: 2024-06-29 15:52:54.902174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838b78bd69b3'
down_revision = '53c29fd98059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('user1_id', sa.INTEGER(), nullable=False),
    sa.Column('user2_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], )
    )
    # ### end Alembic commands ###
